trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Deployment
    displayName: Deployment to AKS cluster (miferrac ns)
    jobs:
      - deployment: canaryDeployment
        environment: miferrac
        displayName: Canary Deployment
        strategy:
          canary:
            increments: [10,20]
            preDeploy:
              steps:
              - script: initialize, cleanup
            deploy:
              steps: 
              - script: echo deploy updates
              - task: KubernetesManifest@0 
                inputs: |
                  action: $(strategy.action)       
                  namespace: 'default'
                  strategy: $(strategy.name)
                  percentage: $(strategy.increment) 
                  manifests: 'manifest.yml' 
            postRouteTraffic: 
              pool: server 
              steps:
              - script: echo monitor application health
            on: 
              failure:
                steps:
                - script: echo clean-up, rollback
              success:
                steps:
                - script: echo checks passed, notify