trigger:
  branches:
    include:
      - miferrac
  paths:
    include:
      - samples/BikeSharingApp/Gateway/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerHub-phenixita'
        repository: 'phenixita/gateway'
        command: 'buildAndPush'
        Dockerfile: 'samples/BikeSharingApp/Gateway/**/Dockerfile'
        tags: '$(tag)'


# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

 