trigger: none

 

parameters:
  - name: buildInput
    type: number
    default: 416
    
variables:
  - template: .ci/yamlVariables.yml

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: DeployCanary
    displayName: Deploy canary
    jobs:
      - deployment: Deploycanary
        environment: expertcluster.bikeapp
        displayName: Canary Deployment
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - task: KubernetesManifest@0
                inputs:
                  action: 'deploy'
                  strategy: 'canary'
                  percentage: '30'
                  manifests: '$(Pipeline.Workspace)/**/reservationEngine-deployment.yaml'
                  containers: 'docker.io/phenixita/reservationengine:${{parameters.buildInput}}'
                displayName: deploy app updates
  - stage: PromoteRejectCanary
    displayName: Promote or Reject canary
    dependsOn: DeployCanary
    condition: succeeded()

    jobs:
    - deployment: PromoteCanary
      displayName: Promote Canary
      pool: 
        vmImage: Ubuntu-latest
      environment: 'expertcluster.bikeapp'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: KubernetesManifest@0
              displayName: promote canary
              inputs:
                action: 'promote'
                strategy: 'canary'
                manifests: '$(Pipeline.Workspace)/**/reservationEngine-deployment.yaml'
                containers: 'docker.io/phenixita/reservationengine:${{parameters.buildInput}}'

  - stage: RejectCanary
    displayName: Reject canary
    dependsOn: PromoteRejectCanary
    condition: failed()

    jobs:
    - deployment: RejectCanary
      displayName: Reject Canary
      pool: 
        vmImage: Ubuntu-latest
      environment: 'expertcluster.bikeapp'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: KubernetesManifest@0
              displayName: reject canary
              inputs:
                action: 'reject'
                strategy: 'canary'
                manifests: '$(Pipeline.Workspace)/**/reservationEngine-deployment.yaml'